// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskConfirm(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AskConfirm'](arg1, arg2, arg3, arg4);
}

export function AskSaveDiscardCancel(arg1, arg2) {
  return window['go']['app']['App']['AskSaveDiscardCancel'](arg1, arg2);
}

export function CancelAIRequest() {
  return window['go']['app']['App']['CancelAIRequest']();
}

export function ClearRecentFiles() {
  return window['go']['app']['App']['ClearRecentFiles']();
}

export function ConfirmOpenExternalURL(arg1) {
  return window['go']['app']['App']['ConfirmOpenExternalURL'](arg1);
}

export function DeleteFileTreePath(arg1) {
  return window['go']['app']['App']['DeleteFileTreePath'](arg1);
}

export function DuplicateFileTreePath(arg1) {
  return window['go']['app']['App']['DuplicateFileTreePath'](arg1);
}

export function FrontendReady() {
  return window['go']['app']['App']['FrontendReady']();
}

export function GetAIModelCatalog(arg1, arg2) {
  return window['go']['app']['App']['GetAIModelCatalog'](arg1, arg2);
}

export function GetAIModelList(arg1, arg2) {
  return window['go']['app']['App']['GetAIModelList'](arg1, arg2);
}

export function GetRecentFiles() {
  return window['go']['app']['App']['GetRecentFiles']();
}

export function GetRelativePath(arg1, arg2) {
  return window['go']['app']['App']['GetRelativePath'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetSystemTheme() {
  return window['go']['app']['App']['GetSystemTheme']();
}

export function GetTranslationTargets(arg1, arg2) {
  return window['go']['app']['App']['GetTranslationTargets'](arg1, arg2);
}

export function GetVersion() {
  return window['go']['app']['App']['GetVersion']();
}

export function HandleFileDrop(arg1) {
  return window['go']['app']['App']['HandleFileDrop'](arg1);
}

export function HandleSecondInstanceLaunch(arg1) {
  return window['go']['app']['App']['HandleSecondInstanceLaunch'](arg1);
}

export function HandleSystemOpenFile(arg1) {
  return window['go']['app']['App']['HandleSystemOpenFile'](arg1);
}

export function InstallSystemIntegration() {
  return window['go']['app']['App']['InstallSystemIntegration']();
}

export function ListFileTree(arg1) {
  return window['go']['app']['App']['ListFileTree'](arg1);
}

export function MakeAIRequest(arg1, arg2, arg3) {
  return window['go']['app']['App']['MakeAIRequest'](arg1, arg2, arg3);
}

export function MakeLMStudioRequest(arg1, arg2, arg3) {
  return window['go']['app']['App']['MakeLMStudioRequest'](arg1, arg2, arg3);
}

export function OpenDirectory() {
  return window['go']['app']['App']['OpenDirectory']();
}

export function OpenExternalPath(arg1) {
  return window['go']['app']['App']['OpenExternalPath'](arg1);
}

export function OpenExternalURL(arg1) {
  return window['go']['app']['App']['OpenExternalURL'](arg1);
}

export function OpenFile() {
  return window['go']['app']['App']['OpenFile']();
}

export function PrintCurrentWindow() {
  return window['go']['app']['App']['PrintCurrentWindow']();
}

export function ReadFile(arg1) {
  return window['go']['app']['App']['ReadFile'](arg1);
}

export function ReadImageAsDataURL(arg1) {
  return window['go']['app']['App']['ReadImageAsDataURL'](arg1);
}

export function RenameFileTreePath(arg1, arg2) {
  return window['go']['app']['App']['RenameFileTreePath'](arg1, arg2);
}

export function SaveFile(arg1, arg2) {
  return window['go']['app']['App']['SaveFile'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function SearchMarkdown(arg1, arg2) {
  return window['go']['app']['App']['SearchMarkdown'](arg1, arg2);
}

export function SelectDocument(arg1) {
  return window['go']['app']['App']['SelectDocument'](arg1);
}

export function SelectImage(arg1) {
  return window['go']['app']['App']['SelectImage'](arg1);
}

export function ShowPageSetup() {
  return window['go']['app']['App']['ShowPageSetup']();
}

export function ShowSaveFileDialog(arg1) {
  return window['go']['app']['App']['ShowSaveFileDialog'](arg1);
}

export function SpellCheckDocument(arg1) {
  return window['go']['app']['App']['SpellCheckDocument'](arg1);
}

export function SyncEditorState(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['SyncEditorState'](arg1, arg2, arg3, arg4, arg5);
}

export function ToggleRecentFilePinned(arg1) {
  return window['go']['app']['App']['ToggleRecentFilePinned'](arg1);
}

export function TouchRecentFile(arg1) {
  return window['go']['app']['App']['TouchRecentFile'](arg1);
}

export function TranslateDocumentCopies(arg1) {
  return window['go']['app']['App']['TranslateDocumentCopies'](arg1);
}

export function UninstallSystemIntegration() {
  return window['go']['app']['App']['UninstallSystemIntegration']();
}

export function UnloadAIModel(arg1, arg2, arg3) {
  return window['go']['app']['App']['UnloadAIModel'](arg1, arg2, arg3);
}
