// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {options} from '../models';

export function AskConfirm(arg1:string,arg2:string,arg3:string,arg4:string):Promise<boolean>;

export function AskSaveDiscardCancel(arg1:string,arg2:string):Promise<string>;

export function CancelAIRequest():Promise<void>;

export function CheckForUpdate():Promise<app.UpdateInfo>;

export function ClearRecentFiles():Promise<void>;

export function ConfirmOpenExternalURL(arg1:string):Promise<boolean>;

export function DeleteFileTreePath(arg1:string):Promise<void>;

export function DuplicateFileTreePath(arg1:string):Promise<string>;

export function FrontendReady():Promise<Array<string>>;

export function GetAIModelCatalog(arg1:string,arg2:Record<string, string>):Promise<Array<app.AIModelInfo>>;

export function GetAIModelList(arg1:string,arg2:Record<string, string>):Promise<Array<string>>;

export function GetRecentFiles():Promise<Array<app.RecentFile>>;

export function GetRelativePath(arg1:string,arg2:string):Promise<string>;

export function GetSettings():Promise<app.AppSettings>;

export function GetSystemFonts():Promise<Array<app.FontInfo>>;

export function GetSystemTheme():Promise<string>;

export function GetTranslationTargets(arg1:string,arg2:Array<app.TranslationLanguage>):Promise<Array<app.TranslatedDocumentTarget>>;

export function GetVersion():Promise<string>;

export function HandleFileDrop(arg1:string):Promise<app.FileResult>;

export function HandleSecondInstanceLaunch(arg1:options.SecondInstanceData):Promise<void>;

export function HandleSystemOpenFile(arg1:string):Promise<void>;

export function InstallSystemIntegration():Promise<string>;

export function ListFileTree(arg1:string):Promise<app.FileTreeNode>;

export function MakeAIRequest(arg1:string,arg2:Record<string, string>,arg3:string):Promise<string>;

export function MakeLMStudioRequest(arg1:string,arg2:Record<string, string>,arg3:string):Promise<string>;

export function OpenDirectory():Promise<string>;

export function OpenExternalPath(arg1:string):Promise<void>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function OpenFile():Promise<app.FileResult>;

export function PrintCurrentWindow():Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function ReadImageAsDataURL(arg1:string):Promise<string>;

export function RenameFileTreePath(arg1:string,arg2:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:app.AppSettings):Promise<void>;

export function SearchMarkdown(arg1:string,arg2:string):Promise<Array<Record<string, string>>>;

export function SelectDocument(arg1:string):Promise<string>;

export function SelectImage(arg1:string):Promise<string>;

export function ShowPageSetup():Promise<void>;

export function ShowSaveFileDialog(arg1:string):Promise<string>;

export function SpellCheckDocument(arg1:app.SpellCheckRequest):Promise<app.SpellCheckResult>;

export function SyncEditorState(arg1:boolean,arg2:boolean,arg3:string,arg4:string,arg5:string):Promise<void>;

export function ToggleRecentFilePinned(arg1:string):Promise<Array<app.RecentFile>>;

export function TouchRecentFile(arg1:string):Promise<void>;

export function TranslateDocumentCopies(arg1:app.TranslateDocumentRequest):Promise<app.TranslatedDocumentResult>;

export function UninstallSystemIntegration():Promise<string>;

export function UnloadAIModel(arg1:string,arg2:Record<string, string>,arg3:string):Promise<void>;
