// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {options} from '../models';

export function ClearRecentFiles():Promise<void>;

export function ConfirmOpenExternalURL(arg1:string):Promise<boolean>;

export function FrontendReady():Promise<Array<string>>;

export function GetRecentFiles():Promise<Array<main.RecentFile>>;

export function GetSettings():Promise<main.AppSettings>;

export function GetSystemTheme():Promise<string>;

export function HandleFileDrop(arg1:string):Promise<main.FileResult>;

export function HandleSecondInstanceLaunch(arg1:options.SecondInstanceData):Promise<void>;

export function HandleSystemOpenFile(arg1:string):Promise<void>;

export function OpenDirectory():Promise<string>;

export function OpenExternalPath(arg1:string):Promise<void>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function OpenFile():Promise<main.FileResult>;

export function ReadFile(arg1:string):Promise<string>;

export function ReadImageAsDataURL(arg1:string):Promise<string>;

export function SaveSettings(arg1:main.AppSettings):Promise<void>;

export function SearchMarkdown(arg1:string,arg2:string):Promise<Array<Record<string, string>>>;
