// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearRecentFiles() {
  return window['go']['main']['App']['ClearRecentFiles']();
}

export function GetRecentFiles() {
  return window['go']['main']['App']['GetRecentFiles']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSystemTheme() {
  return window['go']['main']['App']['GetSystemTheme']();
}

export function HandleFileDrop(arg1) {
  return window['go']['main']['App']['HandleFileDrop'](arg1);
}

export function OpenDirectory() {
  return window['go']['main']['App']['OpenDirectory']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadImageAsDataURL(arg1) {
  return window['go']['main']['App']['ReadImageAsDataURL'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchMarkdown(arg1, arg2) {
  return window['go']['main']['App']['SearchMarkdown'](arg1, arg2);
}
