// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskConfirm(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AskConfirm'](arg1, arg2, arg3, arg4);
}

export function AskSaveDiscardCancel(arg1, arg2) {
  return window['go']['main']['App']['AskSaveDiscardCancel'](arg1, arg2);
}

export function ClearRecentFiles() {
  return window['go']['main']['App']['ClearRecentFiles']();
}

export function ConfirmOpenExternalURL(arg1) {
  return window['go']['main']['App']['ConfirmOpenExternalURL'](arg1);
}

export function FrontendReady() {
  return window['go']['main']['App']['FrontendReady']();
}

export function GetRecentFiles() {
  return window['go']['main']['App']['GetRecentFiles']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSystemTheme() {
  return window['go']['main']['App']['GetSystemTheme']();
}

export function HandleFileDrop(arg1) {
  return window['go']['main']['App']['HandleFileDrop'](arg1);
}

export function HandleSecondInstanceLaunch(arg1) {
  return window['go']['main']['App']['HandleSecondInstanceLaunch'](arg1);
}

export function HandleSystemOpenFile(arg1) {
  return window['go']['main']['App']['HandleSystemOpenFile'](arg1);
}

export function OpenDirectory() {
  return window['go']['main']['App']['OpenDirectory']();
}

export function OpenExternalPath(arg1) {
  return window['go']['main']['App']['OpenExternalPath'](arg1);
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['App']['OpenExternalURL'](arg1);
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadImageAsDataURL(arg1) {
  return window['go']['main']['App']['ReadImageAsDataURL'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchMarkdown(arg1, arg2) {
  return window['go']['main']['App']['SearchMarkdown'](arg1, arg2);
}
