// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskConfirm(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AskConfirm'](arg1, arg2, arg3, arg4);
}

export function AskSaveDiscardCancel(arg1, arg2) {
  return window['go']['main']['App']['AskSaveDiscardCancel'](arg1, arg2);
}

export function CancelAIRequest() {
  return window['go']['main']['App']['CancelAIRequest']();
}

export function ClearRecentFiles() {
  return window['go']['main']['App']['ClearRecentFiles']();
}

export function ConfirmOpenExternalURL(arg1) {
  return window['go']['main']['App']['ConfirmOpenExternalURL'](arg1);
}

export function FrontendReady() {
  return window['go']['main']['App']['FrontendReady']();
}

export function GetAIModelCatalog(arg1, arg2) {
  return window['go']['main']['App']['GetAIModelCatalog'](arg1, arg2);
}

export function GetAIModelList(arg1, arg2) {
  return window['go']['main']['App']['GetAIModelList'](arg1, arg2);
}

export function GetRecentFiles() {
  return window['go']['main']['App']['GetRecentFiles']();
}

export function GetRelativePath(arg1, arg2) {
  return window['go']['main']['App']['GetRelativePath'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSystemTheme() {
  return window['go']['main']['App']['GetSystemTheme']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HandleFileDrop(arg1) {
  return window['go']['main']['App']['HandleFileDrop'](arg1);
}

export function HandleSecondInstanceLaunch(arg1) {
  return window['go']['main']['App']['HandleSecondInstanceLaunch'](arg1);
}

export function HandleSystemOpenFile(arg1) {
  return window['go']['main']['App']['HandleSystemOpenFile'](arg1);
}

export function MakeAIRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['MakeAIRequest'](arg1, arg2, arg3);
}

export function MakeLMStudioRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['MakeLMStudioRequest'](arg1, arg2, arg3);
}

export function OpenDirectory() {
  return window['go']['main']['App']['OpenDirectory']();
}

export function OpenExternalPath(arg1) {
  return window['go']['main']['App']['OpenExternalPath'](arg1);
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['App']['OpenExternalURL'](arg1);
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadImageAsDataURL(arg1) {
  return window['go']['main']['App']['ReadImageAsDataURL'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchMarkdown(arg1, arg2) {
  return window['go']['main']['App']['SearchMarkdown'](arg1, arg2);
}

export function SelectDocument() {
  return window['go']['main']['App']['SelectDocument']();
}

export function SelectImage() {
  return window['go']['main']['App']['SelectImage']();
}

export function ShowSaveFileDialog(arg1) {
  return window['go']['main']['App']['ShowSaveFileDialog'](arg1);
}

export function SyncEditorState(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SyncEditorState'](arg1, arg2, arg3, arg4, arg5);
}

export function TouchRecentFile(arg1) {
  return window['go']['main']['App']['TouchRecentFile'](arg1);
}

export function UnloadAIModel(arg1, arg2, arg3) {
  return window['go']['main']['App']['UnloadAIModel'](arg1, arg2, arg3);
}
